# Generated by Django 5.1.7 on 2025-03-30 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('relationship', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='patient',
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='analysis_actions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='analysis_recommendations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='analysis_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='image_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='image',
            field=models.ImageField(default=False, upload_to='medical_records/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='profile',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='api.profile'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
