# Generated by Django 5.1.7 on 2025-03-30 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profile_remove_medicalrecord_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='raw_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
