# Generated by Django 5.1.7 on 2025-03-30 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_medicalrecord_raw_summary'),
        ('api', '0003_task'),
    ]

    operations = [
    ]
