# Generated by Django 5.1.7 on 2025-03-30 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_merge_0003_medicalrecord_raw_summary_0003_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecord',
            name='raw_summary',
        ),
    ]
