# Generated by Django 5.1.7 on 2025-03-29 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecord',
            name='ai_analysis',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='date',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='image',
        ),
    ]
